"""attempting another db update

Revision ID: 5df2bc9b5dad
Revises: 800930f2c448
Create Date: 2024-05-10 11:45:42.525035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df2bc9b5dad'
down_revision = '800930f2c448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
