"""updated relationships and validations

Revision ID: 800930f2c448
Revises: 0c04cef2feaa
Create Date: 2024-05-09 15:32:37.094653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800930f2c448'
down_revision = '0c04cef2feaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
